# Generated by Django 4.0.5 on 2022-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_options_remove_photo_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='photo',
            name='image2',
            field=models.ImageField(default='good', upload_to=''),
            preserve_default=False,
        ),
    ]
