# Generated by Django 4.0.5 on 2022-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_image_photo_image1_photo_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Photo1',
                'verbose_name_plural': 'Photos1',
            },
        ),
        migrations.CreateModel(
            name='Photo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Photo2',
                'verbose_name_plural': 'Photos2',
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
